version: '3'

services:
  app:
    container_name: MDC
    build: .
    ports:
      - 5000:80
    volumes:
      - ./MyApp/appsettings.json:/app/appsettings.json
      - ./MyApp/bin/Debug/netcoreapp3.1/appLog.txt:/app/appLog.txt
