version: '3.1'

services:
  db:
    container_name: pg
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres: {}
